module.exports = { breakfast: 
   { Grill: 
      [ 'Buttermilk Biscuits',
        'Sausage Gravy',
        'Oatmeal',
        'Omelet Station',
        'Scrambled Eggs',
        'Whole Wheat French Toast',
        'Hard Cooked Cage Free Egg',
        'Home Fried  Potatoes',
        'Frizzled Ham' ] },
  lunch: 
   { 'Entrée': 
      [ 'Chicken and Dumplings',
        'Roasted Corn On The Cob',
        'Broccoli Spears',
        'Louisiana Seafood Gumbo',
        'Grill',
        'Classic Cheeseburger',
        'Cheese Quesadilla',
        'French  Fries',
        'International',
        'Chicken Fried  Rice',
        'Brown Rice' ],
     Pizza: [],
     Grill: [ 'Classic Cheeseburger', 'Cheese Quesadilla', 'French  Fries' ],
     International: 
      [ 'Chicken Fried  Rice',
        'Brown Rice',
        'Pizza',
        'Cheese Pizza',
        'Pepperoni Pizza',
        'Eggplant Parmesan Pizzetta' ],
     Salad: 
      [ 'Chicken Caesar Salad',
        'Greek Side Salad',
        'Theme Cuisine',
        'Whole Wheat Penne Noodles',
        'Spaghetti Sauce with Tomato Bits',
        'Farfalle Alfredo Casserette' ],
     'Vegetarian/Vegan': 
      [ 'Carrot & Celery Sticks',
        'Braised Kale',
        'Hummus',
        'Couscous Pepper, Olive & Pine Nut Salad',
        'White Bean & Caramelized Onion Salad',
        'Curried Vegetable  Salad',
        'Tropical Salsa',
        'Pico de Gallo',
        'Spicy Eggplant with Garbanzo Beans',
        'Couscous',
        'Baked  Potato',
        'Baked Sweet Potatoes',
        'White Bean Chili with Wheat Berries' ],
     'Simple Servings': 
      [ 'Simple Cranberry Glazed Pork Cutlet',
        'Whole Green Beans',
        'Baked Potato',
        'Green Lentils',
        'Green Pepper & Tomato Salad',
        'Mixed Green Salad',
        'Stone Ground Balsamic Vinaigrette' ] },
  dinner: 
   { 'Entrée': 
      [ 'Steamed Fresh Baby Carrots',
        'Corn & Lobster Risotto',
        'Grill',
        'Classic Cheeseburger',
        'Cheese Quesadilla',
        'French  Fries',
        'International',
        'Curried Chicken',
        'Jasmine Rice',
        'Brown Rice' ],
     Pizza: [],
     Grill: [ 'Classic Cheeseburger', 'Cheese Quesadilla', 'French  Fries' ],
     International: 
      [ 'Curried Chicken',
        'Jasmine Rice',
        'Brown Rice',
        'Pizza',
        'Cheese Pizza',
        'Pepperoni Pizza',
        'Eggplant Parmesan Pizzetta' ],
     Salad: 
      [ 'Chicken Caesar Salad',
        'Greek Side Salad',
        'Theme Cuisine',
        'Whole Wheat Penne Noodles',
        'Spaghetti Sauce with Tomato Bits',
        'Farfalle Alfredo Casserette' ],
     'Vegetarian/Vegan': 
      [ 'Carrot & Celery Sticks',
        'Braised Kale',
        'Hummus',
        'Couscous Pepper, Olive & Pine Nut Salad',
        'White Bean & Caramelized Onion Salad',
        'Curried Vegetable  Salad',
        'Tropical Salsa',
        'Pico de Gallo',
        'Sweet & Sour Tofu Stir Fry',
        'Jasmine Rice',
        'Baked  Potato',
        'Baked Sweet Potatoes',
        'White Bean Chili with Wheat Berries' ],
     'Simple Servings': 
      [ 'Cajun  Chicken Breast',
        'Quinoa Primavera',
        'Broccoli Cuts',
        'Green Lentils',
        'Green Pepper & Tomato Salad',
        'Mixed Green Salad' ] },
  late_night: 
   { 'Entrée': 
      [ 'Chicken and Dumplings',
        'Roasted Corn On The Cob',
        'Broccoli Spears',
        'Louisiana Seafood Gumbo',
        'Grill',
        'Classic Cheeseburger',
        'Cheese Quesadilla',
        'French  Fries',
        'International',
        'Chicken Fried  Rice',
        'Brown Rice' ],
     Pizza: [],
     Grill: 
      [ 'Buttermilk Biscuits',
        'Sausage Gravy',
        'Oatmeal',
        'Omelet Station',
        'Scrambled Eggs',
        'Whole Wheat French Toast',
        'Hard Cooked Cage Free Egg',
        'Home Fried  Potatoes',
        'Frizzled Ham',
        'LUNCH',
        'Deli',
        'Chicken Caesar Wrap',
        'Mediterranean Spinach Petite Wrap',
        'Marinated Bean Salad with Cumin',
        'Carolina Chopped Slaw',
        'Fripps Potato Chips Snack',
        'Bagel w/ Egg, Cheese & Bacon',
        'Sausage & Mushroom Flatbread Melt',
        'English Muffin w/ Egg & Cheese',
        'Grilled Cheese with Tomatoes on Wheat',
        'Grilled Three Cheese & Herbs on White',
        'Entrée',
        'Chicken and Dumplings',
        'Roasted Corn On The Cob',
        'Broccoli Spears',
        'Louisiana Seafood Gumbo',
        'Grill',
        'Classic Cheeseburger',
        'Cheese Quesadilla',
        'French  Fries' ],
     International: 
      [ 'Chicken Fried  Rice',
        'Brown Rice',
        'Pizza',
        'Cheese Pizza',
        'Pepperoni Pizza',
        'Eggplant Parmesan Pizzetta' ],
     Salad: 
      [ 'Chicken Caesar Salad',
        'Greek Side Salad',
        'Theme Cuisine',
        'Whole Wheat Penne Noodles',
        'Spaghetti Sauce with Tomato Bits',
        'Farfalle Alfredo Casserette' ],
     'Vegetarian/Vegan': 
      [ 'Carrot & Celery Sticks',
        'Braised Kale',
        'Hummus',
        'Couscous Pepper, Olive & Pine Nut Salad',
        'White Bean & Caramelized Onion Salad',
        'Curried Vegetable  Salad',
        'Tropical Salsa',
        'Pico de Gallo',
        'Spicy Eggplant with Garbanzo Beans',
        'Couscous',
        'Baked  Potato',
        'Baked Sweet Potatoes',
        'White Bean Chili with Wheat Berries' ],
     'Simple Servings': 
      [ 'Simple Cranberry Glazed Pork Cutlet',
        'Whole Green Beans',
        'Baked Potato',
        'Green Lentils',
        'Green Pepper & Tomato Salad',
        'Mixed Green Salad',
        'Stone Ground Balsamic Vinaigrette',
        'DINNER',
        'Deli',
        'Chicken Caesar Wrap',
        'Mediterranean Spinach Petite Wrap',
        'Marinated Bean Salad with Cumin',
        'Carolina Chopped Slaw',
        'English Muffin w/ Egg & Cheese',
        'Bagel w/ Egg, Cheese & Bacon',
        'Sausage & Mushroom Flatbread Melt',
        'Grilled Cheese with Tomatoes on Wheat',
        'Grilled Three Cheese & Herbs on White',
        'Entrée',
        'Steamed Fresh Baby Carrots',
        'Corn & Lobster Risotto',
        'Grill',
        'Classic Cheeseburger',
        'Cheese Quesadilla',
        'French  Fries',
        'International',
        'Curried Chicken',
        'Jasmine Rice',
        'Brown Rice',
        'Pizza',
        'Cheese Pizza',
        'Pepperoni Pizza',
        'Eggplant Parmesan Pizzetta',
        'Salad',
        'Chicken Caesar Salad',
        'Greek Side Salad',
        'Theme Cuisine',
        'Whole Wheat Penne Noodles',
        'Spaghetti Sauce with Tomato Bits',
        'Farfalle Alfredo Casserette',
        'Vegetarian/Vegan',
        'Carrot & Celery Sticks',
        'Braised Kale',
        'Hummus',
        'Couscous Pepper, Olive & Pine Nut Salad',
        'White Bean & Caramelized Onion Salad',
        'Curried Vegetable  Salad',
        'Tropical Salsa',
        'Pico de Gallo',
        'Sweet & Sour Tofu Stir Fry',
        'Jasmine Rice',
        'Baked  Potato',
        'Baked Sweet Potatoes',
        'White Bean Chili with Wheat Berries',
        'Simple Servings',
        'Cajun  Chicken Breast',
        'Quinoa Primavera',
        'Broccoli Cuts',
        'Green Lentils',
        'Green Pepper & Tomato Salad',
        'Mixed Green Salad',
        'Stone Ground Balsamic Vinaigrette' ] } }