module.exports = { breakfast: 
   { Grill: 
      [ 'Oatmeal',
        'Omelet Station',
        'Scrambled Eggs',
        'Banana Pancakes',
        'Hard Cooked Cage Free Egg',
        'French Fried Tater Tots',
        'Mushroom, Spinach & Swiss Breakfast Bowl' ] },
  lunch: 
   { 'Entrée': 
      [ 'Grilled Fiesta Lime Chicken Fajita',
        'Mexican  Brown Rice',
        'Roasted Corn',
        'Cajun Crab (Surimi) Muffuletta Sandwich',
        'Tossed Salad',
        'Grill',
        'Cheese, Kale & Red Onions Flatbread',
        'Ham, Swiss &Spicy Mustard Flatbread Melt',
        'French  Fries',
        'International',
        'Chicken Fried  Rice',
        'Brown Rice' ],
     Pizza: [],
     Grill: 
      [ 'Cheese, Kale & Red Onions Flatbread',
        'Ham, Swiss &Spicy Mustard Flatbread Melt',
        'French  Fries' ],
     International: 
      [ 'Chicken Fried  Rice',
        'Brown Rice',
        'Pizza',
        'Scratch Cheese Pizza',
        'Pepperoni Pizza',
        'Chicken Cacciatore Pizzetta',
        'Herb Seasoned Breadsticks',
        'Spaghetti Sauce with Tomato Bits' ],
     Salad: 
      [ 'Chicken Caesar Salad',
        'Tossed Garden Salad',
        'Spinach, Barley, Pepper & Olive Salad' ],
     Soup: 
      [ 'Tomato Florentine Soup',
        'Lima Bean and Tomato Soup',
        'Old-Fashioned Chicken Noodle Soup',
        'Soft Dinner Roll Dough',
        'Theme Cuisine',
        'Garlic Parmesan Breadsticks',
        'Alfredo Sauce',
        'Rotini, Whole Wheat, Dry',
        'Farfalle Alfredo Casserette' ],
     'Vegetarian/Vegan': 
      [ 'Hummus',
        'Braised Kale',
        'Lemony Chickpea Salad',
        'Corn, Tomato, & Basil Salad',
        'Farro Salad with Garden Vegetables',
        'Sun-Dried Tomato Cucumber Relish',
        'Chipotle Ancho Salsa',
        'Sesame Coated Tofu',
        'Jasmine Rice',
        'Bok Choy & Shiitake Mushroom with Sesame',
        'Vegetable Chili',
        'Simple Baked Sweet Potato',
        'Baked Potato',
        'Carrot Apple Smoothie',
        'Carrot & Celery Sticks' ],
     'Simple Servings': 
      [ 'Mushroom Chili',
        'Cilantro Slaw',
        'Grit Cakes with Red Onion',
        'Green Lentils',
        'Sliced Red Potatoes with Vinaigrette',
        'Citrus Spiced Lentil Salad' ] },
  dinner: 
   { 'Entrée': 
      [ 'Maple Peach Glazed Ham',
        'Scalloped Potato',
        'Green Peas',
        'Chile Rubbed Tilapia Plate',
        'Grill',
        'Burrito Bar',
        'International',
        'Beef Curry With Thai Eggplant',
        'Jasmine Rice',
        'Brown Rice' ],
     Pizza: [],
     Grill: [ 'Burrito Bar' ],
     International: 
      [ 'Beef Curry With Thai Eggplant',
        'Jasmine Rice',
        'Brown Rice',
        'Pizza',
        'Cheese Pizza',
        'Pepperoni Pizza',
        'Chicken Cacciatore Pizzetta',
        'Herb Seasoned Breadsticks',
        'Spaghetti Sauce with Tomato Bits' ],
     Salad: 
      [ 'Chicken Caesar Salad',
        'Tossed Garden Salad',
        'Spinach, Barley, Pepper & Olive Salad' ],
     Soup: 
      [ 'Tomato Florentine Soup',
        'Lima Bean and Tomato Soup',
        'Old-Fashioned Chicken Noodle Soup',
        'Soft Dinner Roll Dough',
        'Theme Cuisine',
        'Garlic Parmesan Breadsticks',
        'Alfredo Sauce',
        'Whole Wheat Rotini',
        'Farfalle Alfredo Casserette' ],
     'Vegetarian/Vegan': 
      [ 'Carrot Apple Smoothie',
        'Tri-Color Tortilla Chips',
        'Braised Kale',
        'Hummus',
        'Lemony Chickpea Salad',
        'Corn, Tomato, & Basil Salad',
        'Farro Salad with Garden Vegetables',
        'Sun-Dried Tomato Cucumber Relish',
        'Chipotle Ancho Salsa',
        'Vegan Chow Mein with Cashews',
        'Vegetable Chili',
        'Simple Baked Sweet Potato',
        'Baked Potato',
        'Carrot & Celery Sticks' ],
     'Simple Servings': 
      [ 'Tilapia Fillets',
        'Italian Vegetable Blend',
        'Coastal Style White Rice',
        'Green Lentils',
        'Sliced Red Potatoes with Vinaigrette',
        'Citrus Spiced Lentil Salad' ] } }
