module.exports = { breakfast: 
   { 'Entrée': 
      [ 'Sausage Gravy & Biscuit',
        'Oatmeal',
        'Scrambled  Eggs',
        'Buttermilk Whole Wheat Pancakes',
        'French Fried Tater Tots',
        'Turkey Sausage Links',
        'Hard Cooked Cage Free Egg' ],
     Exhibition: [ 'Omelet Bar' ],
     Pizza: [ 'Bagel with Eggs & Ham' ] },
  lunch: 
   { 'Entrée': 
      [ 'Vegetarian Paella',
        'Broccoli Spears',
        'Baked Garlic Flatbread Strips' ],
     Exhibition: 
      [ 'Shell Pasta',
        'Whole Wheat Penne',
        'Spaghetti Sauce with Tomato Bits',
        'Alfredo Sauce',
        'Rigatoni Arrabiata Casserette',
        'Herb Seasoned Breadsticks',
        'Grill',
        'Chicken Sandwich',
        'Grilled Cheese',
        'French  Fries',
        'International',
        'Scratch Gyro Bar' ],
     Pizza: [],
     Grill: [ 'Chicken Sandwich', 'Grilled Cheese', 'French  Fries' ],
     International: 
      [ 'Scratch Gyro Bar',
        'Pizza',
        'Antipasto Pizza Slice',
        'Pepperoni Pizza',
        'Margherita Pizza',
        'Herb Seasoned Breadsticks' ],
     Salad: 
      [ 'Salad Bar Station',
        'Mediterranean Chicken Salad',
        'Tossed Vegetable Salad',
        'Cilantro Lime Soy Dressing' ],
     Soup: 
      [ 'Tomato Soup Florentine',
        'Chicken Noodle Soup with Fresh Dill' ],
     'Vegetarian/Vegan': 
      [ 'Pita Chips',
        'Hummus',
        'Broccoli, Olives & Sun Dried Tomatoes',
        'Lentils and Swiss Chard',
        'Turkish Bulgur Pilaf with Garbanzo Beans',
        'Roasted Onion-Habanero Salsa',
        'Melon Jalapeno Salsa',
        'Banana Smoothie',
        'Sun-Dried Tomato & Gorgonzola Bruschetta',
        'Spanish-Style Garbanzo Beans',
        'Baked Sweet Potatoes',
        'Baked  Potato',
        'Vegetarian Chili' ],
     'Simple Servings': 
      [ 'Thick & Zesty Turkey Chili',
        'Polenta with Caramelized Onions',
        'Whole Green Beans' ] },
  dinner: 
   { 'Entrée': 
      [ 'Cheese Enchiladas',
        'Black Bean & Corn Salsa',
        'Arroz Verde',
        'Aztec Corn',
        'Roasted Southwestern Vegetables' ],
     Exhibition: 
      [ 'Shell Pasta',
        'Whole Wheat Penne',
        'Spaghetti Sauce with Tomato Bits',
        'Alfredo Sauce',
        'Rigatoni Arrabiata Casserette',
        'Herb Seasoned Breadsticks',
        'Grill',
        'Kansas City BBQ Pulled Pork Sandwich',
        'Grilled Cheese & Tomato Sandwich',
        'French  Fries',
        'International',
        'Scratch Gyro Bar' ],
     Pizza: [],
     Grill: 
      [ 'Kansas City BBQ Pulled Pork Sandwich',
        'Grilled Cheese & Tomato Sandwich',
        'French  Fries' ],
     International: 
      [ 'Scratch Gyro Bar',
        'Pizza',
        'Antipasto Pizza Slice',
        'Pepperoni Pizza',
        'Margherita Pizza' ],
     Salad: 
      [ 'Salad Bar Station',
        'Mediterranean Chicken Salad',
        'Tossed Vegetable Salad',
        'Cilantro Lime Soy Dressing' ],
     Soup: 
      [ 'Tomato Soup Florentine',
        'Chicken Noodle Soup with Fresh Dill' ],
     'Vegetarian/Vegan': 
      [ 'Fripps Potato Chips Snack',
        'Hummus',
        'Broccoli, Olives & Sun Dried Tomatoes',
        'Lentils and Swiss Chard',
        'Turkish Bulgur Pilaf with Garbanzo Beans',
        'Roasted Onion-Habanero Salsa',
        'Melon Jalapeno Salsa',
        'Banana Smoothie',
        'Quinoa Salad Plate',
        'Eggplant Caponata Griddle Sandwich',
        'Baked  Potato',
        'Vegetarian Chili',
        'Baked Sweet Potato' ],
     'Simple Servings': 
      [ 'Italian Style Pork Loin',
        'Simple Pan Fried Falafel',
        'Jasmine Rice',
        'Cucumber  Salad' ] },
  late_night: { 'Entrée': [ 'Fried Rice Bar' ] } }